# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

def fib_gene():
    a, b = 1, 1
    while True:
        yield b
        a, b = b, a+b
        
fib = fib_gene()
n = next(fib)
res = 0
while n <= 4e6:
    if n%2 == 0:
        res += n
    n = next(fib)
print(res)