'''The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?'''


import math

def triangular_gene():
    i = 1
    j = 2
    while True:
        yield i
        i += j
        j += 1

def num_factor(x):
    n = 0
    for i in range(2, int(math.sqrt(x))+1):
        if x%i == 0:
            n += 1
            if i != x/i:
                n += 1
    return (n+2)

def isTriangleNumber(n):
    a = int(sqrt(2*n))
    return 0.5*a*(a+1) == n
            
def tau(num):
    n = num
    i = 2
    p = 1
    if (num == 1):
        return 1
    while (i * i <= n):
        c = 1
        while (n % i == 0):
            n /= i
            c += 1
        i += 1
        p *= c
    if (n == num or n > 1):
        p *= 2
    return p

if __name__ == '__main__':
    import time
    
    start_time = time.time()
    t = triangular_gene()
    x = next(t)
    while tau(x) <= 500:
        x = next(t)
    print(x)
    print("Time elapsed:", time.time() - start_time)

    
